const MIGRATIONS_TABLE_SQL: string = `CREATE TABLE IF NOT EXISTS migrations ( 
id INT AUTO_INCREMENT PRIMARY KEY,
filename VARCHAR(255) NOT NULL UNIQUE,
applied_at VARCHAR(30) DEFAULT NULL
);`;

export default MIGRATIONS_TABLE_SQL;
