const MIGRATIONS_TABLE_SQL: string = `CREATE TABLE IF NOT EXISTS migrations ( 
id INT AUTO_INCREMENT PRIMARY KEY,
filename VARCHAR(255) NOT NULL UNIQUE,
applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);`;

export default MIGRATIONS_TABLE_SQL;